// <auto-generated />
using GarphIt.api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GarphIt.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201007090807_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphIt.models.Edge", b =>
                {
                    b.Property<int>("EdgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EdgeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeadId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TailId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("EdgeId");

                    b.ToTable("Edges");

                    b.HasData(
                        new
                        {
                            EdgeId = 1,
                            EdgeColor = "#000000",
                            HeadId = 1,
                            Label = "Hello",
                            LabelColor = "#dd1122",
                            TailId = 2,
                            Weight = 10.119999999999999
                        });
                });

            modelBuilder.Entity("GraphIt.models.Node", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Xaxis")
                        .HasColumnType("float");

                    b.Property<double>("Yaxis")
                        .HasColumnType("float");

                    b.HasKey("NodeId");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            NodeId = 1,
                            Label = "Hello",
                            LabelColor = "#dd1122",
                            NodeColor = "#000000",
                            Xaxis = 10.119999999999999,
                            Yaxis = 11.109999999999999
                        },
                        new
                        {
                            NodeId = 2,
                            Label = "Bye",
                            LabelColor = "#aabbcc",
                            NodeColor = "#123456",
                            Xaxis = 1.0,
                            Yaxis = 13.44
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
